#+options: toc:nil date:nil title:nil num:nil
#+latex_header: \input{settings}

* D9 Ten career-best academic research outputs

- * Ben Andrews, \textbf{Paul Bryan}. \emph{Curvature bounds by isoperimetric comparison for normalized Ricci flow on the two-sphere}. Calc. Var. Partial Differential Equations 39, 419--428, 2010.

   \emph{Developed striking new techniques for obtaining direct curvature and isoperimetric control for the Ricci flow. Provides a very short and direct proof of the main convergence results for the Rici flow on the sphere by developing a viscosity comparison theory for the isoperimetric profile.}

- * Ben Andrews, \textbf{Paul Bryan}. \emph{A comparison theorem for the isoperimetric profile under curve-shortening flow}. Comm. Anal. Geom. 19, 503--539, 2011.

  \emph{Isoperimetric profile comparisons obtained for the curvature flow. These are similar to the Ricci flow, but includes boundary terms that make the analysis significantly more involved.}

- * Ben Andrews, \textbf{Paul Bryan}. \emph{Curvature bound for curve shortening flow via distance comparison and a direct proof of Grayson's theorem}. J. Reine Angew. Math. 653, 179--187. 2011.

  \emph{This is know by many experts as the "go to" proof of the main convergence results for the curve shortening flow. A very direct proof is obtained using distance comparison with sharp comparisons for a viscosity equation. Significant simplifications and clarity are obtained compared with previous proofs.}

- * \textbf{Paul Bryan} \emph{Curvature bounds via an isoperimetric comparison for Ricci flow on surfaces} Ann. Scuola Norm. Sup. Pisa Cl. Sci September 2016, Volume 16, Issue 3

  \emph{Extends the Ricci flow two sphere result to arbitrary closed surfaces. A number of innovations are introduced such as lifting the flow to the universal conver and dealing with the lack of compactness.}

- \textbf{Paul Bryan}, Janelle Louie \emph{Classification of Convex Ancient Solutions to Curve Shortening Flow on the Sphere} J. Geom. Anal. April 2016, Volume 26, Issue 2, 858--872

  \emph{Only classification result know for non-planar curve shortening flow. Initiated the Harnack inequality in non-Euclidean backgrounds and developed the Aleksandrov reflection technique.}

- \textbf{Paul Bryan}, Mohammad Ivaki, Julian Scheuer \emph{Harnack inequalities for evolving hypersurfaces on the sphere} Comm. Anal Geom. (Accepted) 2016 arXiv: [math.DG] (available at \url{http://arxiv.org/abs/1512.03374})

  \emph{First example of Harnack inequality for hypersurface flows in higher dimension non Euclidean Riemannian manifolds. Extends Hamilton's approach for the Mean Curvature Flow in Euclidean space to a broader class of flows and non-Euclidean backgrounds. This iniated the continuing study of Harnack inequalities in non Euclidean background spaces.}
